### ISSUE TITLE
Canvas

### ISSUE THREAD

**Issue by Catvert** [michaelfairley/rust-imgui-sdl2#2]
Hi !
I have an issue when I want to use the canvas with imgui.
Windows are completely white or blinking. I have reuse your demo to try.
This is the code I have tried : 
```rust
...
let mut canvas = window.into_canvas().build().unwrap();
'running: loop {
        use sdl2::event::Event;
        use sdl2::keyboard::Keycode;

        for event in event_pump.poll_iter() {
            imgui_sdl2.handle_event(&mut imgui, &event);
            if imgui_sdl2.ignore_event(&event) { continue; }

            match event {
                Event::Quit {..} | Event::KeyDown { keycode: Some(Keycode::Escape), .. } => {
                    break 'running
                },
                _ => {}
            }
        }

        let ui = imgui_sdl2.frame(&canvas.window(), &mut imgui, &event_pump);

        ui.show_test_window(&mut true);

        unsafe {
            gl::ClearColor(0.2, 0.2, 0.2, 1.0);
            gl::Clear(gl::COLOR_BUFFER_BIT);
        }

        renderer.render(ui);

        canvas.window.gl_swap_window();

        canvas.present();

        ::std::thread::sleep(::std::time::Duration::new(0, 1_000_000_000u32 / 60));
    }
```
Thanks for your help,
Catvert.

**Comment by michaelfairley** [comment]
Mixing SDL's renderer (`Canvas`) and other OpenGL calls (from imgui-opengl-renderer) is generally going to be a little tough.

There _might_ be some ways for me to make this situation better in the library (I'm still thinking through how to do so), but for now, as a workaround, you can a) switch the current GL context before any non-Canvas OpenGL calls (including `renderer.render(ui)`), and b) call `gl::Flush()` between any OpenGL calls and any canvas calls, like so:

```rust
    canvas.window_mut().gl_make_current(&gl_context).unwrap();
    unsafe {
      gl::ClearColor(0.2, 0.2, 0.8, 1.0);
      gl::Clear(gl::COLOR_BUFFER_BIT);
    }
    unsafe{ gl::Flush() };

    canvas.set_draw_color(sdl2::pixels::Color::RGB(200, 20, 20));
    canvas.draw_rect(sdl2::rect::Rect::new(100, 100, 200, 200)).unwrap();
    unsafe{ gl::Flush() };

    canvas.window_mut().gl_make_current(&gl_context).unwrap();
    renderer.render(ui);
    unsafe{ gl::Flush() };

    canvas.present();
```

It's definitely not great (and it might perform poorly), but it'll probably work?

There's also a decent change this _won't_ work on Windows since the SDL renderer will usually default to using Direct X. 😐

**Comment by Catvert** [comment]
Thanks for your help, I'll see how it goes and do some research.

**Comment by miwarnec** [comment]
Hey @Catvert did you ever figure this out?
